const vocabData = {
  'N5': [
    {word:'私',kana:'わたし',zh:'我',en:'I/me'},
    {word:'あなた',kana:'あなた',zh:'你',en:'you'},
    {word:'彼',kana:'かれ',zh:'他',en:'he'},
    {word:'彼女',kana:'かのじょ',zh:'她',en:'she'},
    {word:'私たち',kana:'わたしたち',zh:'我們',en:'we'},
    {word:'皆さん',kana:'みなさん',zh:'大家',en:'everyone'},
    {word:'人',kana:'ひと',zh:'人',en:'person'},
    {word:'男',kana:'おとこ',zh:'男人',en:'man'},
    {word:'女',kana:'おんな',zh:'女人',en:'woman'},
    {word:'子供',kana:'こども',zh:'小孩',en:'child'},
    {word:'父',kana:'ちち',zh:'父親',en:'father'},
    {word:'母',kana:'はは',zh:'母親',en:'mother'},
    {word:'兄',kana:'あに',zh:'哥哥',en:'older brother'},
    {word:'姉',kana:'あね',zh:'姊姊',en:'older sister'},
    {word:'弟',kana:'おとうと',zh:'弟弟',en:'younger brother'},
    {word:'妹',kana:'いもうと',zh:'妹妹',en:'younger sister'},
    {word:'友達',kana:'ともだち',zh:'朋友',en:'friend'},
    {word:'先生',kana:'せんせい',zh:'老師',en:'teacher'},
    {word:'学生',kana:'がくせい',zh:'學生',en:'student'},
    {word:'会社員',kana:'かいしゃいん',zh:'公司職員',en:'office worker'},
    {word:'日本',kana:'にほん',zh:'日本',en:'Japan'},
    {word:'中国',kana:'ちゅうごく',zh:'中國',en:'China'},
    {word:'韓国',kana:'かんこく',zh:'韓國',en:'Korea'},
    {word:'アメリカ',kana:'あめりか',zh:'美國',en:'America'},
    {word:'英語',kana:'えいご',zh:'英文',en:'English'},
    {word:'日本語',kana:'にほんご',zh:'日文',en:'Japanese'},
    {word:'学校',kana:'がっこう',zh:'學校',en:'school'},
    {word:'大学',kana:'だいがく',zh:'大學',en:'university'},
    {word:'家',kana:'いえ',zh:'家',en:'house/home'},
    {word:'部屋',kana:'へや',zh:'房間',en:'room'},
    {word:'会社',kana:'かいしゃ',zh:'公司',en:'company'},
    {word:'病院',kana:'びょういん',zh:'醫院',en:'hospital'},
    {word:'駅',kana:'えき',zh:'車站',en:'station'},
    {word:'電車',kana:'でんしゃ',zh:'電車',en:'train'},
    {word:'バス',kana:'ばす',zh:'公車',en:'bus'},
    {word:'車',kana:'くるま',zh:'車子',en:'car'},
    {word:'自転車',kana:'じてんしゃ',zh:'腳踏車',en:'bicycle'},
    {word:'飛行機',kana:'ひこうき',zh:'飛機',en:'airplane'},
    {word:'電話',kana:'でんわ',zh:'電話',en:'telephone'},
    {word:'本',kana:'ほん',zh:'書',en:'book'},
    {word:'新聞',kana:'しんぶん',zh:'報紙',en:'newspaper'},
    {word:'雑誌',kana:'ざっし',zh:'雜誌',en:'magazine'},
    {word:'テレビ',kana:'てれび',zh:'電視',en:'television'},
    {word:'ラジオ',kana:'らじお',zh:'收音機',en:'radio'},
    {word:'音楽',kana:'おんがく',zh:'音樂',en:'music'},
    {word:'映画',kana:'えいが',zh:'電影',en:'movie'},
    {word:'写真',kana:'しゃしん',zh:'照片',en:'photo'},
    {word:'時計',kana:'とけい',zh:'時鐘/手錶',en:'clock/watch'},
    {word:'鉛筆',kana:'えんぴつ',zh:'鉛筆',en:'pencil'},
    {word:'ペン',kana:'ぺん',zh:'筆',en:'pen'},
    {word:'机',kana:'つくえ',zh:'書桌',en:'desk'},
    {word:'椅子',kana:'いす',zh:'椅子',en:'chair'},
    {word:'ドア',kana:'どあ',zh:'門',en:'door'},
    {word:'窓',kana:'まど',zh:'窗戶',en:'window'},
    {word:'水',kana:'みず',zh:'水',en:'water'},
    {word:'お茶',kana:'おちゃ',zh:'茶',en:'tea'},
    {word:'コーヒー',kana:'こーひー',zh:'咖啡',en:'coffee'},
    {word:'ご飯',kana:'ごはん',zh:'飯',en:'rice/meal'},
    {word:'パン',kana:'ぱん',zh:'麵包',en:'bread'},
    {word:'魚',kana:'さかな',zh:'魚',en:'fish'},
    {word:'肉',kana:'にく',zh:'肉',en:'meat'},
    {word:'野菜',kana:'やさい',zh:'蔬菜',en:'vegetable'},
    {word:'果物',kana:'くだもの',zh:'水果',en:'fruit'},
    {word:'卵',kana:'たまご',zh:'雞蛋',en:'egg'},
    {word:'牛乳',kana:'ぎゅうにゅう',zh:'牛奶',en:'milk'},
    {word:'お酒',kana:'おさけ',zh:'酒',en:'alcohol'},
    {word:'ビール',kana:'びーる',zh:'啤酒',en:'beer'},
    {word:'山',kana:'やま',zh:'山',en:'mountain'},
    {word:'川',kana:'かわ',zh:'河川',en:'river'},
    {word:'海',kana:'うみ',zh:'海',en:'sea'},
    {word:'空',kana:'そら',zh:'天空',en:'sky'},
    {word:'花',kana:'はな',zh:'花',en:'flower'},
    {word:'木',kana:'き',zh:'樹木',en:'tree'},
    {word:'犬',kana:'いぬ',zh:'狗',en:'dog'},
    {word:'猫',kana:'ねこ',zh:'貓',en:'cat'},
    {word:'春',kana:'はる',zh:'春天',en:'spring'},
    {word:'夏',kana:'なつ',zh:'夏天',en:'summer'},
    {word:'秋',kana:'あき',zh:'秋天',en:'autumn'},
    {word:'冬',kana:'ふゆ',zh:'冬天',en:'winter'},
    {word:'今日',kana:'きょう',zh:'今天',en:'today'},
    {word:'明日',kana:'あした',zh:'明天',en:'tomorrow'},
    {word:'昨日',kana:'きのう',zh:'昨天',en:'yesterday'},
    {word:'今',kana:'いま',zh:'現在',en:'now'},
    {word:'朝',kana:'あさ',zh:'早上',en:'morning'},
    {word:'昼',kana:'ひる',zh:'中午',en:'noon'},
    {word:'夜',kana:'よる',zh:'晚上',en:'night'},
    {word:'年',kana:'とし',zh:'年',en:'year'},
    {word:'月',kana:'つき',zh:'月',en:'month'},
    {word:'週',kana:'しゅう',zh:'週',en:'week'},
    {word:'時間',kana:'じかん',zh:'時間',en:'time/hour'},
    {word:'一',kana:'いち',zh:'一',en:'one'},
    {word:'二',kana:'に',zh:'二',en:'two'},
    {word:'三',kana:'さん',zh:'三',en:'three'},
    {word:'四',kana:'し/よん',zh:'四',en:'four'},
    {word:'五',kana:'ご',zh:'五',en:'five'},
    {word:'百',kana:'ひゃく',zh:'一百',en:'hundred'},
    {word:'千',kana:'せん',zh:'一千',en:'thousand'},
    {word:'食べる',kana:'たべる',zh:'吃',en:'to eat'},
    {word:'飲む',kana:'のむ',zh:'喝',en:'to drink'},
    {word:'見る',kana:'みる',zh:'看',en:'to see/watch'},
    {word:'聞く',kana:'きく',zh:'聽/問',en:'to listen/ask'},
    {word:'話す',kana:'はなす',zh:'說話',en:'to speak'},
    {word:'読む',kana:'よむ',zh:'讀',en:'to read'},
    {word:'書く',kana:'かく',zh:'寫',en:'to write'},
    {word:'行く',kana:'いく',zh:'去',en:'to go'},
    {word:'来る',kana:'くる',zh:'來',en:'to come'},
    {word:'帰る',kana:'かえる',zh:'回去',en:'to return'},
    {word:'起きる',kana:'おきる',zh:'起床',en:'to wake up'},
    {word:'寝る',kana:'ねる',zh:'睡覺',en:'to sleep'},
    {word:'買う',kana:'かう',zh:'買',en:'to buy'},
    {word:'売る',kana:'うる',zh:'賣',en:'to sell'},
    {word:'使う',kana:'つかう',zh:'使用',en:'to use'},
    {word:'作る',kana:'つくる',zh:'製作',en:'to make'},
    {word:'大きい',kana:'おおきい',zh:'大的',en:'big'},
    {word:'小さい',kana:'ちいさい',zh:'小的',en:'small'},
    {word:'高い',kana:'たかい',zh:'高的/貴的',en:'tall/expensive'},
    {word:'安い',kana:'やすい',zh:'便宜的',en:'cheap'},
    {word:'新しい',kana:'あたらしい',zh:'新的',en:'new'},
    {word:'古い',kana:'ふるい',zh:'舊的',en:'old'},
    {word:'良い',kana:'よい/いい',zh:'好的',en:'good'},
    {word:'悪い',kana:'わるい',zh:'壞的',en:'bad'},
    {word:'多い',kana:'おおい',zh:'多的',en:'many'},
    {word:'少ない',kana:'すくない',zh:'少的',en:'few'},
    {word:'暑い',kana:'あつい',zh:'熱的',en:'hot'},
    {word:'寒い',kana:'さむい',zh:'冷的',en:'cold'},
    {word:'面白い',kana:'おもしろい',zh:'有趣的',en:'interesting'},
    {word:'難しい',kana:'むずかしい',zh:'難的',en:'difficult'},
    {word:'易しい',kana:'やさしい',zh:'簡單的',en:'easy'},
    {word:'きれい',kana:'きれい',zh:'漂亮的/乾淨的',en:'pretty/clean'},
    {word:'静か',kana:'しずか',zh:'安靜的',en:'quiet'},
    {word:'元気',kana:'げんき',zh:'精神好的',en:'healthy/energetic'},
    {word:'好き',kana:'すき',zh:'喜歡',en:'to like'},
    {word:'嫌い',kana:'きらい',zh:'討厭',en:'to dislike'},
    {word:'上',kana:'うえ',zh:'上面',en:'above/up'},
    {word:'下',kana:'した',zh:'下面',en:'below/down'},
    {word:'右',kana:'みぎ',zh:'右邊',en:'right'},
    {word:'左',kana:'ひだり',zh:'左邊',en:'left'},
    {word:'前',kana:'まえ',zh:'前面',en:'front'},
    {word:'後ろ',kana:'うしろ',zh:'後面',en:'behind'},
    {word:'中',kana:'なか',zh:'裡面',en:'inside'},
    {word:'外',kana:'そと',zh:'外面',en:'outside'},
    {word:'はい',kana:'はい',zh:'是',en:'yes'},
    {word:'いいえ',kana:'いいえ',zh:'不是',en:'no'},
    {word:'ありがとう',kana:'ありがとう',zh:'謝謝',en:'thank you'},
    {word:'すみません',kana:'すみません',zh:'對不起/不好意思',en:'excuse me/sorry'},
    {word:'お願い',kana:'おねがい',zh:'拜託',en:'please'},
    {word:'どうぞ',kana:'どうぞ',zh:'請',en:'please go ahead'},
    {word:'いくら',kana:'いくら',zh:'多少錢',en:'how much'}
  ],
  'N4': [
    {word:'準備',kana:'じゅんび',zh:'準備',en:'preparation'},
    {word:'連絡',kana:'れんらく',zh:'聯絡',en:'contact'},
    {word:'約束',kana:'やくそく',zh:'約定',en:'promise'},
    {word:'説明',kana:'せつめい',zh:'說明',en:'explanation'},
    {word:'練習',kana:'れんしゅう',zh:'練習',en:'practice'},
    {word:'勉強',kana:'べんきょう',zh:'學習',en:'study'},
    {word:'授業',kana:'じゅぎょう',zh:'課程',en:'class/lesson'},
    {word:'試験',kana:'しけん',zh:'考試',en:'exam'},
    {word:'宿題',kana:'しゅくだい',zh:'作業',en:'homework'},
    {word:'答え',kana:'こたえ',zh:'答案',en:'answer'},
    {word:'質問',kana:'しつもん',zh:'問題',en:'question'},
    {word:'意見',kana:'いけん',zh:'意見',en:'opinion'},
    {word:'会議',kana:'かいぎ',zh:'會議',en:'meeting'},
    {word:'仕事',kana:'しごと',zh:'工作',en:'work/job'},
    {word:'休み',kana:'やすみ',zh:'休假/休息',en:'holiday/rest'},
    {word:'生活',kana:'せいかつ',zh:'生活',en:'life/living'},
    {word:'旅行',kana:'りょこう',zh:'旅行',en:'travel'},
    {word:'経験',kana:'けいけん',zh:'經驗',en:'experience'},
    {word:'運動',kana:'うんどう',zh:'運動',en:'exercise'},
    {word:'料理',kana:'りょうり',zh:'料理',en:'cooking/dish'},
    {word:'買い物',kana:'かいもの',zh:'購物',en:'shopping'},
    {word:'お金',kana:'おかね',zh:'錢',en:'money'},
    {word:'値段',kana:'ねだん',zh:'價格',en:'price'},
    {word:'銀行',kana:'ぎんこう',zh:'銀行',en:'bank'},
    {word:'郵便局',kana:'ゆうびんきょく',zh:'郵局',en:'post office'},
    {word:'交番',kana:'こうばん',zh:'派出所',en:'police box'},
    {word:'図書館',kana:'としょかん',zh:'圖書館',en:'library'},
    {word:'公園',kana:'こうえん',zh:'公園',en:'park'},
    {word:'地図',kana:'ちず',zh:'地圖',en:'map'},
    {word:'住所',kana:'じゅうしょ',zh:'地址',en:'address'},
    {word:'道',kana:'みち',zh:'道路',en:'road/way'},
    {word:'電気',kana:'でんき',zh:'電氣/電燈',en:'electricity/light'},
    {word:'ガス',kana:'がす',zh:'瓦斯',en:'gas'},
    {word:'水道',kana:'すいどう',zh:'自來水',en:'water supply'},
    {word:'天気',kana:'てんき',zh:'天氣',en:'weather'},
    {word:'雨',kana:'あめ',zh:'雨',en:'rain'},
    {word:'雪',kana:'ゆき',zh:'雪',en:'snow'},
    {word:'風',kana:'かぜ',zh:'風',en:'wind'},
    {word:'温度',kana:'おんど',zh:'溫度',en:'temperature'},
    {word:'季節',kana:'きせつ',zh:'季節',en:'season'},
    {word:'服',kana:'ふく',zh:'衣服',en:'clothes'},
    {word:'靴',kana:'くつ',zh:'鞋子',en:'shoes'},
    {word:'帽子',kana:'ぼうし',zh:'帽子',en:'hat'},
    {word:'財布',kana:'さいふ',zh:'錢包',en:'wallet'},
    {word:'眼鏡',kana:'めがね',zh:'眼鏡',en:'glasses'},
    {word:'鍵',kana:'かぎ',zh:'鑰匙',en:'key'},
    {word:'荷物',kana:'にもつ',zh:'行李',en:'luggage'},
    {word:'手紙',kana:'てがみ',zh:'信',en:'letter'},
    {word:'葉書',kana:'はがき',zh:'明信片',en:'postcard'},
    {word:'切手',kana:'きって',zh:'郵票',en:'stamp'},
    {word:'プレゼント',kana:'ぷれぜんと',zh:'禮物',en:'present/gift'},
    {word:'病気',kana:'びょうき',zh:'生病',en:'illness'},
    {word:'薬',kana:'くすり',zh:'藥',en:'medicine'},
    {word:'頭',kana:'あたま',zh:'頭',en:'head'},
    {word:'顔',kana:'かお',zh:'臉',en:'face'},
    {word:'目',kana:'め',zh:'眼睛',en:'eye'},
    {word:'耳',kana:'みみ',zh:'耳朵',en:'ear'},
    {word:'口',kana:'くち',zh:'嘴巴',en:'mouth'},
    {word:'手',kana:'て',zh:'手',en:'hand'},
    {word:'足',kana:'あし',zh:'腳',en:'foot/leg'},
    {word:'体',kana:'からだ',zh:'身體',en:'body'},
    {word:'心',kana:'こころ',zh:'心',en:'heart/mind'},
    {word:'声',kana:'こえ',zh:'聲音',en:'voice'},
    {word:'気持ち',kana:'きもち',zh:'心情',en:'feeling'},
    {word:'笑う',kana:'わらう',zh:'笑',en:'to laugh/smile'},
    {word:'泣く',kana:'なく',zh:'哭',en:'to cry'},
    {word:'怒る',kana:'おこる',zh:'生氣',en:'to get angry'},
    {word:'心配する',kana:'しんぱいする',zh:'擔心',en:'to worry'},
    {word:'嬉しい',kana:'うれしい',zh:'高興的',en:'happy'},
    {word:'悲しい',kana:'かなしい',zh:'悲傷的',en:'sad'},
    {word:'怖い',kana:'こわい',zh:'可怕的',en:'scary'},
    {word:'恥ずかしい',kana:'はずかしい',zh:'害羞的',en:'embarrassed'},
    {word:'寂しい',kana:'さびしい',zh:'寂寞的',en:'lonely'},
    {word:'忙しい',kana:'いそがしい',zh:'忙碌的',en:'busy'},
    {word:'暇',kana:'ひま',zh:'空閒的',en:'free time'},
    {word:'急ぐ',kana:'いそぐ',zh:'趕快',en:'to hurry'},
    {word:'待つ',kana:'まつ',zh:'等待',en:'to wait'},
    {word:'始まる',kana:'はじまる',zh:'開始',en:'to begin'},
    {word:'終わる',kana:'おわる',zh:'結束',en:'to end'},
    {word:'続ける',kana:'つづける',zh:'繼續',en:'to continue'},
    {word:'止める',kana:'やめる',zh:'停止',en:'to stop/quit'},
    {word:'決める',kana:'きめる',zh:'決定',en:'to decide'},
    {word:'選ぶ',kana:'えらぶ',zh:'選擇',en:'to choose'},
    {word:'比べる',kana:'くらべる',zh:'比較',en:'to compare'},
    {word:'集める',kana:'あつめる',zh:'收集',en:'to collect'},
    {word:'出す',kana:'だす',zh:'取出/交出',en:'to take out/submit'},
    {word:'入れる',kana:'いれる',zh:'放入',en:'to put in'},
    {word:'開ける',kana:'あける',zh:'打開',en:'to open'},
    {word:'閉める',kana:'しめる',zh:'關閉',en:'to close'},
    {word:'貸す',kana:'かす',zh:'借出',en:'to lend'},
    {word:'借りる',kana:'かりる',zh:'借入',en:'to borrow'},
    {word:'返す',kana:'かえす',zh:'歸還',en:'to return'},
    {word:'洗う',kana:'あらう',zh:'洗',en:'to wash'},
    {word:'掃除する',kana:'そうじする',zh:'打掃',en:'to clean'},
    {word:'料理する',kana:'りょうりする',zh:'做料理',en:'to cook'},
    {word:'着る',kana:'きる',zh:'穿（上衣）',en:'to wear (top)'},
    {word:'脱ぐ',kana:'ぬぐ',zh:'脫衣服',en:'to take off clothes'},
    {word:'習う',kana:'ならう',zh:'學習',en:'to learn'},
    {word:'教える',kana:'おしえる',zh:'教導',en:'to teach'},
    {word:'知る',kana:'しる',zh:'知道',en:'to know'},
    {word:'忘れる',kana:'わすれる',zh:'忘記',en:'to forget'},
    {word:'覚える',kana:'おぼえる',zh:'記住',en:'to remember'},
    {word:'わかる',kana:'わかる',zh:'明白',en:'to understand'},
    {word:'大切',kana:'たいせつ',zh:'重要的',en:'important/precious'},
    {word:'大丈夫',kana:'だいじょうぶ',zh:'沒關係',en:'all right/okay'},
    {word:'特別',kana:'とくべつ',zh:'特別',en:'special'},
    {word:'普通',kana:'ふつう',zh:'普通',en:'normal/ordinary'},
    {word:'一緒',kana:'いっしょ',zh:'一起',en:'together'},
    {word:'もう',kana:'もう',zh:'已經',en:'already'},
    {word:'まだ',kana:'まだ',zh:'還',en:'still/yet'},
    {word:'また',kana:'また',zh:'又/再',en:'again'},
    {word:'もっと',kana:'もっと',zh:'更多',en:'more'},
    {word:'ちょっと',kana:'ちょっと',zh:'一點',en:'a little'},
    {word:'たぶん',kana:'たぶん',zh:'大概',en:'probably'},
    {word:'本当',kana:'ほんとう',zh:'真的',en:'really/true'},
    {word:'大体',kana:'だいたい',zh:'大概',en:'generally'}
  ],
  'N3': [
    {word:'影響',kana:'えいきょう',zh:'影響',en:'influence/effect'},
    {word:'環境',kana:'かんきょう',zh:'環境',en:'environment'},
    {word:'問題',kana:'もんだい',zh:'問題',en:'problem'},
    {word:'原因',kana:'げんいん',zh:'原因',en:'cause/reason'},
    {word:'結果',kana:'けっか',zh:'結果',en:'result'},
    {word:'目的',kana:'もくてき',zh:'目的',en:'purpose/goal'},
    {word:'方法',kana:'ほうほう',zh:'方法',en:'method/way'},
    {word:'理由',kana:'りゆう',zh:'理由',en:'reason'},
    {word:'例',kana:'れい',zh:'例子',en:'example'},
    {word:'場合',kana:'ばあい',zh:'情況',en:'case/situation'},
    {word:'状況',kana:'じょうきょう',zh:'狀況',en:'situation'},
    {word:'機会',kana:'きかい',zh:'機會',en:'opportunity'},
    {word:'必要',kana:'ひつよう',zh:'必要',en:'necessary'},
    {word:'重要',kana:'じゅうよう',zh:'重要',en:'important'},
    {word:'可能',kana:'かのう',zh:'可能',en:'possible'},
    {word:'様々',kana:'さまざま',zh:'各種各樣',en:'various'},
    {word:'一般的',kana:'いっぱんてき',zh:'一般的',en:'general'},
    {word:'具体的',kana:'ぐたいてき',zh:'具體的',en:'specific/concrete'},
    {word:'積極的',kana:'せっきょくてき',zh:'積極的',en:'positive/proactive'},
    {word:'消極的',kana:'しょうきょくてき',zh:'消極的',en:'passive/negative'},
    {word:'自由',kana:'じゆう',zh:'自由',en:'freedom'},
    {word:'平和',kana:'へいわ',zh:'和平',en:'peace'},
    {word:'安全',kana:'あんぜん',zh:'安全',en:'safe'},
    {word:'危険',kana:'きけん',zh:'危險',en:'dangerous'},
    {word:'便利',kana:'べんり',zh:'方便',en:'convenient'},
    {word:'不便',kana:'ふべん',zh:'不方便',en:'inconvenient'},
    {word:'正確',kana:'せいかく',zh:'正確',en:'accurate'},
    {word:'失敗',kana:'しっぱい',zh:'失敗',en:'failure'},
    {word:'成功',kana:'せいこう',zh:'成功',en:'success'},
    {word:'努力',kana:'どりょく',zh:'努力',en:'effort'},
    {word:'成長',kana:'せいちょう',zh:'成長',en:'growth'},
    {word:'発展',kana:'はってん',zh:'發展',en:'development'},
    {word:'変化',kana:'へんか',zh:'變化',en:'change'},
    {word:'改善',kana:'かいぜん',zh:'改善',en:'improvement'},
    {word:'解決',kana:'かいけつ',zh:'解決',en:'solution'},
    {word:'発見',kana:'はっけん',zh:'發現',en:'discovery'},
    {word:'調査',kana:'ちょうさ',zh:'調查',en:'investigation'},
    {word:'研究',kana:'けんきゅう',zh:'研究',en:'research'},
    {word:'技術',kana:'ぎじゅつ',zh:'技術',en:'technology/skill'},
    {word:'情報',kana:'じょうほう',zh:'資訊',en:'information'},
    {word:'文化',kana:'ぶんか',zh:'文化',en:'culture'},
    {word:'伝統',kana:'でんとう',zh:'傳統',en:'tradition'},
    {word:'習慣',kana:'しゅうかん',zh:'習慣',en:'habit/custom'},
    {word:'社会',kana:'しゃかい',zh:'社會',en:'society'},
    {word:'政治',kana:'せいじ',zh:'政治',en:'politics'},
    {word:'経済',kana:'けいざい',zh:'經濟',en:'economy'},
    {word:'医療',kana:'いりょう',zh:'醫療',en:'medical care'},
    {word:'福祉',kana:'ふくし',zh:'福利',en:'welfare'},
    {word:'教育',kana:'きょういく',zh:'教育',en:'education'},
    {word:'試合',kana:'しあい',zh:'比賽',en:'match/game'},
    {word:'競争',kana:'きょうそう',zh:'競爭',en:'competition'},
    {word:'記録',kana:'きろく',zh:'記錄',en:'record'},
    {word:'結婚',kana:'けっこん',zh:'結婚',en:'marriage'},
    {word:'離婚',kana:'りこん',zh:'離婚',en:'divorce'},
    {word:'出産',kana:'しゅっさん',zh:'生產/生小孩',en:'childbirth'},
    {word:'家族',kana:'かぞく',zh:'家族/家人',en:'family'},
    {word:'親',kana:'おや',zh:'父母',en:'parent'},
    {word:'祖父母',kana:'そふぼ',zh:'祖父母',en:'grandparents'},
    {word:'孫',kana:'まご',zh:'孫子',en:'grandchild'},
    {word:'近所',kana:'きんじょ',zh:'鄰居',en:'neighborhood'},
    {word:'地域',kana:'ちいき',zh:'地區',en:'region/area'},
    {word:'地方',kana:'ちほう',zh:'地方',en:'region/locality'},
    {word:'都市',kana:'とし',zh:'都市',en:'city'},
    {word:'田舎',kana:'いなか',zh:'鄉下',en:'countryside'},
    {word:'気候',kana:'きこう',zh:'氣候',en:'climate'},
    {word:'自然',kana:'しぜん',zh:'自然',en:'nature'},
    {word:'植物',kana:'しょくぶつ',zh:'植物',en:'plant'},
    {word:'動物',kana:'どうぶつ',zh:'動物',en:'animal'},
    {word:'生き物',kana:'いきもの',zh:'生物',en:'living creature'},
    {word:'空気',kana:'くうき',zh:'空氣',en:'air'},
    {word:'土',kana:'つち',zh:'土壤',en:'soil/earth'},
    {word:'石',kana:'いし',zh:'石頭',en:'stone'},
    {word:'火',kana:'ひ',zh:'火',en:'fire'},
    {word:'光',kana:'ひかり',zh:'光',en:'light'},
    {word:'影',kana:'かげ',zh:'影子',en:'shadow'},
    {word:'色',kana:'いろ',zh:'顏色',en:'color'},
    {word:'形',kana:'かたち',zh:'形狀',en:'shape'},
    {word:'大きさ',kana:'おおきさ',zh:'大小',en:'size'},
    {word:'重さ',kana:'おもさ',zh:'重量',en:'weight'},
    {word:'速さ',kana:'はやさ',zh:'速度',en:'speed'},
    {word:'深い',kana:'ふかい',zh:'深的',en:'deep'},
    {word:'浅い',kana:'あさい',zh:'淺的',en:'shallow'},
    {word:'広い',kana:'ひろい',zh:'寬廣的',en:'wide/spacious'},
    {word:'狭い',kana:'せまい',zh:'狹窄的',en:'narrow'},
    {word:'長い',kana:'ながい',zh:'長的',en:'long'},
    {word:'短い',kana:'みじかい',zh:'短的',en:'short'},
    {word:'丸い',kana:'まるい',zh:'圓的',en:'round'},
    {word:'四角い',kana:'しかくい',zh:'方形的',en:'square'},
    {word:'柔らかい',kana:'やわらかい',zh:'柔軟的',en:'soft'},
    {word:'硬い',kana:'かたい',zh:'硬的',en:'hard/tough'},
    {word:'重い',kana:'おもい',zh:'重的',en:'heavy'},
    {word:'軽い',kana:'かるい',zh:'輕的',en:'light'},
    {word:'甘い',kana:'あまい',zh:'甜的',en:'sweet'},
    {word:'辛い',kana:'からい',zh:'辣的/鹹的',en:'spicy/salty'},
    {word:'苦い',kana:'にがい',zh:'苦的',en:'bitter'},
    {word:'酸っぱい',kana:'すっぱい',zh:'酸的',en:'sour'},
    {word:'美味しい',kana:'おいしい',zh:'好吃的',en:'delicious'},
    {word:'まずい',kana:'まずい',zh:'難吃的',en:'bad taste'},
    {word:'驚く',kana:'おどろく',zh:'驚訝',en:'to be surprised'},
    {word:'喜ぶ',kana:'よろこぶ',zh:'高興',en:'to be pleased'},
    {word:'困る',kana:'こまる',zh:'困擾',en:'to be in trouble'},
    {word:'諦める',kana:'あきらめる',zh:'放棄',en:'to give up'},
    {word:'挑戦する',kana:'ちょうせんする',zh:'挑戰',en:'to challenge'},
    {word:'参加する',kana:'さんかする',zh:'參加',en:'to participate'},
    {word:'経験する',kana:'けいけんする',zh:'經歷',en:'to experience'},
    {word:'確認する',kana:'かくにんする',zh:'確認',en:'to confirm'},
    {word:'相談する',kana:'そうだんする',zh:'商量',en:'to consult'},
    {word:'反省する',kana:'はんせいする',zh:'反省',en:'to reflect on'},
    {word:'尊敬する',kana:'そんけいする',zh:'尊敬',en:'to respect'},
    {word:'感謝する',kana:'かんしゃする',zh:'感謝',en:'to be grateful'},
    {word:'期待する',kana:'きたいする',zh:'期待',en:'to expect/look forward to'},
    {word:'信じる',kana:'しんじる',zh:'相信',en:'to believe'},
    {word:'疑う',kana:'うたがう',zh:'懷疑',en:'to doubt'},
    {word:'想像する',kana:'そうぞうする',zh:'想像',en:'to imagine'},
    {word:'計画する',kana:'けいかくする',zh:'計畫',en:'to plan'},
    {word:'準備する',kana:'じゅんびする',zh:'準備',en:'to prepare'},
    {word:'発表する',kana:'はっぴょうする',zh:'發表',en:'to announce/present'},
    {word:'報告する',kana:'ほうこくする',zh:'報告',en:'to report'},
    {word:'説明する',kana:'せつめいする',zh:'說明',en:'to explain'},
    {word:'理解する',kana:'りかいする',zh:'理解',en:'to understand'}
  ],
  'N2': [
    {word:'矛盾',kana:'むじゅん',zh:'矛盾',en:'contradiction'},
    {word:'妥協',kana:'だきょう',zh:'妥協',en:'compromise'},
    {word:'柔軟',kana:'じゅうなん',zh:'柔軟靈活',en:'flexible'},
    {word:'概念',kana:'がいねん',zh:'概念',en:'concept'},
    {word:'抽象',kana:'ちゅうしょう',zh:'抽象',en:'abstract'},
    {word:'具体',kana:'ぐたい',zh:'具體',en:'concrete'},
    {word:'論理',kana:'ろんり',zh:'邏輯',en:'logic'},
    {word:'根拠',kana:'こんきょ',zh:'根據',en:'basis/grounds'},
    {word:'傾向',kana:'けいこう',zh:'傾向',en:'tendency/trend'},
    {word:'特徴',kana:'とくちょう',zh:'特徵',en:'characteristic/feature'},
    {word:'観点',kana:'かんてん',zh:'觀點',en:'viewpoint'},
    {word:'立場',kana:'たちば',zh:'立場',en:'standpoint/position'},
    {word:'態度',kana:'たいど',zh:'態度',en:'attitude'},
    {word:'姿勢',kana:'しせい',zh:'姿態/態度',en:'posture/attitude'},
    {word:'方針',kana:'ほうしん',zh:'方針',en:'policy/direction'},
    {word:'対策',kana:'たいさく',zh:'對策',en:'countermeasure'},
    {word:'手段',kana:'しゅだん',zh:'手段',en:'means/measure'},
    {word:'条件',kana:'じょうけん',zh:'條件',en:'condition'},
    {word:'要因',kana:'よういん',zh:'要因',en:'factor/cause'},
    {word:'背景',kana:'はいけい',zh:'背景',en:'background'},
    {word:'過程',kana:'かてい',zh:'過程',en:'process'},
    {word:'段階',kana:'だんかい',zh:'階段',en:'stage/phase'},
    {word:'基準',kana:'きじゅん',zh:'基準',en:'standard/criteria'},
    {word:'評価',kana:'ひょうか',zh:'評價',en:'evaluation'},
    {word:'批判',kana:'ひはん',zh:'批判',en:'criticism'},
    {word:'賛成',kana:'さんせい',zh:'贊成',en:'agreement/approval'},
    {word:'反対',kana:'はんたい',zh:'反對',en:'opposition'},
    {word:'妥当',kana:'だとう',zh:'妥當',en:'appropriate/valid'},
    {word:'合理的',kana:'ごうりてき',zh:'合理的',en:'rational/reasonable'},
    {word:'効率的',kana:'こうりつてき',zh:'有效率的',en:'efficient'},
    {word:'系統的',kana:'けいとうてき',zh:'系統性的',en:'systematic'},
    {word:'持続可能',kana:'じぞくかのう',zh:'可持續的',en:'sustainable'},
    {word:'多様性',kana:'たようせい',zh:'多樣性',en:'diversity'},
    {word:'共存',kana:'きょうそん',zh:'共存',en:'coexistence'},
    {word:'協力',kana:'きょうりょく',zh:'協力',en:'cooperation'},
    {word:'連携',kana:'れんけい',zh:'聯繫合作',en:'coordination/cooperation'},
    {word:'統合',kana:'とうごう',zh:'統合',en:'integration'},
    {word:'分析',kana:'ぶんせき',zh:'分析',en:'analysis'},
    {word:'比較',kana:'ひかく',zh:'比較',en:'comparison'},
    {word:'考察',kana:'こうさつ',zh:'考察',en:'examination/study'},
    {word:'検討',kana:'けんとう',zh:'檢討',en:'review/consideration'},
    {word:'議論',kana:'ぎろん',zh:'議論',en:'argument/discussion'},
    {word:'主張',kana:'しゅちょう',zh:'主張',en:'assertion/claim'},
    {word:'証明',kana:'しょうめい',zh:'證明',en:'proof/verification'},
    {word:'根本的',kana:'こんぽんてき',zh:'根本的',en:'fundamental'},
    {word:'本質的',kana:'ほんしつてき',zh:'本質的',en:'essential'},
    {word:'表面的',kana:'ひょうめんてき',zh:'表面的',en:'superficial'},
    {word:'副作用',kana:'ふくさよう',zh:'副作用',en:'side effect'},
    {word:'障害',kana:'しょうがい',zh:'障礙',en:'obstacle/disability'},
    {word:'克服',kana:'こくふく',zh:'克服',en:'overcome'},
    {word:'促進',kana:'そくしん',zh:'促進',en:'promotion/facilitation'},
    {word:'抑制',kana:'よくせい',zh:'抑制',en:'suppression/control'},
    {word:'維持',kana:'いじ',zh:'維持',en:'maintenance'},
    {word:'確保',kana:'かくほ',zh:'確保',en:'to secure/ensure'},
    {word:'実現',kana:'じつげん',zh:'實現',en:'realization'},
    {word:'達成',kana:'たっせい',zh:'達成',en:'achievement'},
    {word:'貢献',kana:'こうけん',zh:'貢獻',en:'contribution'},
    {word:'配慮',kana:'はいりょ',zh:'配慮',en:'consideration/thoughtfulness'},
    {word:'把握',kana:'はあく',zh:'掌握',en:'grasp/understanding'},
    {word:'懸念',kana:'けねん',zh:'疑慮',en:'concern/apprehension'},
    {word:'著しい',kana:'いちじるしい',zh:'顯著的',en:'remarkable/notable'},
    {word:'僅か',kana:'わずか',zh:'僅僅',en:'only a little/mere'},
    {word:'絶えず',kana:'たえず',zh:'不斷地',en:'constantly'},
    {word:'敢えて',kana:'あえて',zh:'敢於/特意',en:'dare to/boldly'},
    {word:'もはや',kana:'もはや',zh:'已不再',en:'no longer'},
    {word:'かつて',kana:'かつて',zh:'曾經',en:'once/formerly'},
    {word:'おそらく',kana:'おそらく',zh:'大概/恐怕',en:'probably/perhaps'},
    {word:'いわば',kana:'いわば',zh:'所謂',en:'so to speak'},
    {word:'むしろ',kana:'むしろ',zh:'寧可',en:'rather/instead'},
    {word:'いっぽう',kana:'いっぽう',zh:'另一方面',en:'on the other hand'},
    {word:'したがって',kana:'したがって',zh:'因此',en:'therefore'},
    {word:'にもかかわらず',kana:'にもかかわらず',zh:'儘管如此',en:'despite/in spite of'},
    {word:'に関して',kana:'にかんして',zh:'關於',en:'regarding/concerning'},
    {word:'を通じて',kana:'をつうじて',zh:'通過',en:'through/via'},
    {word:'に伴い',kana:'にともない',zh:'隨著',en:'accompanied by'},
    {word:'に基づき',kana:'にもとづき',zh:'基於',en:'based on'},
    {word:'に際して',kana:'にさいして',zh:'在...之際',en:'on the occasion of'},
    {word:'に対して',kana:'にたいして',zh:'對於',en:'toward/against'},
    {word:'において',kana:'において',zh:'在...方面',en:'in/at/regarding'},
    {word:'をはじめ',kana:'をはじめ',zh:'以...為首',en:'starting with'},
    {word:'ものの',kana:'ものの',zh:'雖然',en:'although/even though'},
    {word:'ことから',kana:'ことから',zh:'由於',en:'from the fact that'},
    {word:'わけだ',kana:'わけだ',zh:'就是說',en:'that means/no wonder'},
    {word:'ようだ',kana:'ようだ',zh:'好像',en:'seems like/appears to be'},
    {word:'わけではない',kana:'わけではない',zh:'並不是',en:'it does not mean that'},
    {word:'にすぎない',kana:'にすぎない',zh:'不過是',en:'no more than/merely'},
    {word:'に違いない',kana:'にちがいない',zh:'一定是',en:'must be/no doubt'},
    {word:'はずがない',kana:'はずがない',zh:'不可能是',en:'cannot possibly be'},
    {word:'に際し',kana:'にさいし',zh:'在...的時候',en:'on the occasion of'},
    {word:'目安',kana:'めやす',zh:'目標/標準',en:'target/guideline'},
    {word:'余裕',kana:'よゆう',zh:'餘裕',en:'margin/leeway'},
    {word:'限界',kana:'げんかい',zh:'極限',en:'limit/boundary'},
    {word:'課題',kana:'かだい',zh:'課題',en:'issue/assignment'},
    {word:'展望',kana:'てんぼう',zh:'展望',en:'view/prospect'},
    {word:'見解',kana:'けんかい',zh:'見解',en:'view/opinion'},
    {word:'提案',kana:'ていあん',zh:'提案',en:'proposal'},
    {word:'実施',kana:'じっし',zh:'實施',en:'implementation'},
    {word:'施策',kana:'しさく',zh:'施策',en:'measure/policy'},
    {word:'転換',kana:'てんかん',zh:'轉換',en:'conversion/shift'},
    {word:'革新',kana:'かくしん',zh:'革新',en:'innovation/reform'},
    {word:'体制',kana:'たいせい',zh:'體制',en:'system/setup'},
    {word:'組織',kana:'そしき',zh:'組織',en:'organization'},
    {word:'権限',kana:'けんげん',zh:'權限',en:'authority/jurisdiction'},
    {word:'責任',kana:'せきにん',zh:'責任',en:'responsibility'},
    {word:'義務',kana:'ぎむ',zh:'義務',en:'obligation/duty'},
    {word:'権利',kana:'けんり',zh:'權利',en:'right'}
  ],
  'N1': [
    {word:'躊躇',kana:'ちゅうちょ',zh:'猶豫',en:'hesitation'},
    {word:'払拭',kana:'ふっしょく',zh:'消除',en:'to sweep away'},
    {word:'一蹴',kana:'いっしゅう',zh:'一口拒絕',en:'to reject flatly'},
    {word:'蔓延',kana:'まんえん',zh:'蔓延',en:'to spread'},
    {word:'顕著',kana:'けんちょ',zh:'顯著',en:'remarkable'},
    {word:'逡巡',kana:'しゅんじゅん',zh:'猶豫不決',en:'hesitation/vacillation'},
    {word:'捏造',kana:'ねつぞう',zh:'捏造',en:'fabrication/forgery'},
    {word:'暴露',kana:'ばくろ',zh:'曝光/揭露',en:'exposure/revelation'},
    {word:'隠蔽',kana:'いんぺい',zh:'隱瞞',en:'concealment/cover-up'},
    {word:'抹消',kana:'まっしょう',zh:'抹除',en:'erasure/deletion'},
    {word:'欺瞞',kana:'ぎまん',zh:'欺騙',en:'deception'},
    {word:'真摯',kana:'しんし',zh:'真摯',en:'sincere/earnest'},
    {word:'真剣',kana:'しんけん',zh:'認真',en:'serious/earnest'},
    {word:'慎重',kana:'しんちょう',zh:'慎重',en:'careful/cautious'},
    {word:'大胆',kana:'だいたん',zh:'大膽',en:'bold/daring'},
    {word:'冷静',kana:'れいせい',zh:'冷靜',en:'calm/composed'},
    {word:'沈着',kana:'ちんちゃく',zh:'沉著',en:'composed/calm'},
    {word:'果敢',kana:'かかん',zh:'果敢',en:'bold/courageous'},
    {word:'卓越',kana:'たくえつ',zh:'卓越',en:'excellence/superiority'},
    {word:'秀逸',kana:'しゅういつ',zh:'優秀出色',en:'excellent/superb'},
    {word:'斬新',kana:'ざんしん',zh:'新穎',en:'novel/innovative'},
    {word:'陳腐',kana:'ちんぷ',zh:'陳腐',en:'stale/hackneyed'},
    {word:'斬る',kana:'きる',zh:'斬斷',en:'to cut/slash'},
    {word:'凌ぐ',kana:'しのぐ',zh:'忍耐/超越',en:'to endure/surpass'},
    {word:'凌駕',kana:'りょうが',zh:'凌駕',en:'to surpass/dominate'},
    {word:'覆す',kana:'くつがえす',zh:'推翻',en:'to overturn/overturn'},
    {word:'揺るがす',kana:'ゆるがす',zh:'動搖',en:'to shake/rock'},
    {word:'踏みにじる',kana:'ふみにじる',zh:'踐踏',en:'to trample on'},
    {word:'根絶',kana:'こんぜつ',zh:'根絕',en:'eradication'},
    {word:'撲滅',kana:'ぼくめつ',zh:'撲滅',en:'extermination'},
    {word:'啓発',kana:'けいはつ',zh:'啟發',en:'enlightenment'},
    {word:'鼓舞',kana:'こぶ',zh:'鼓舞',en:'encouragement/inspiration'},
    {word:'叱咤',kana:'しった',zh:'激勵',en:'to encourage/cheer on'},
    {word:'奮起',kana:'ふんき',zh:'奮起',en:'to rouse oneself'},
    {word:'自覚',kana:'じかく',zh:'自覺',en:'self-awareness'},
    {word:'模索',kana:'もさく',zh:'摸索',en:'groping/fumbling'},
    {word:'葛藤',kana:'かっとう',zh:'葛藤/糾葛',en:'conflict/inner struggle'},
    {word:'苦悩',kana:'くのう',zh:'苦惱',en:'anguish/agony'},
    {word:'煩悶',kana:'はんもん',zh:'煩悶',en:'anguish/worry'},
    {word:'憂鬱',kana:'ゆううつ',zh:'憂鬱',en:'melancholy/depression'},
    {word:'恍惚',kana:'こうこつ',zh:'恍惚',en:'ecstasy/rapture'},
    {word:'陶酔',kana:'とうすい',zh:'陶醉',en:'intoxication/rapture'},
    {word:'感銘',kana:'かんめい',zh:'感銘',en:'deep impression'},
    {word:'共鳴',kana:'きょうめい',zh:'共鳴',en:'resonance/sympathy'},
    {word:'思惟',kana:'しい',zh:'思惟',en:'thought/thinking'},
    {word:'洞察',kana:'どうさつ',zh:'洞察',en:'insight'},
    {word:'直感',kana:'ちょっかん',zh:'直覺',en:'intuition'},
    {word:'逆説',kana:'ぎゃくせつ',zh:'悖論',en:'paradox'},
    {word:'命題',kana:'めいだい',zh:'命題',en:'proposition'},
    {word:'仮説',kana:'かせつ',zh:'假說',en:'hypothesis'},
    {word:'定義',kana:'ていぎ',zh:'定義',en:'definition'},
    {word:'範疇',kana:'はんちゅう',zh:'範疇',en:'category'},
    {word:'概括',kana:'がいかつ',zh:'概括',en:'generalization'},
    {word:'省察',kana:'せいさつ',zh:'省察',en:'reflection/introspection'},
    {word:'峻別',kana:'しゅんべつ',zh:'嚴格區別',en:'strict distinction'},
    {word:'截然',kana:'せつぜん',zh:'截然',en:'clearly/distinctly'},
    {word:'曖昧',kana:'あいまい',zh:'曖昧模糊',en:'ambiguous/vague'},
    {word:'錯綜',kana:'さくそう',zh:'錯綜複雜',en:'complicated/intricate'},
    {word:'乖離',kana:'かいり',zh:'背離',en:'divergence/deviation'},
    {word:'齟齬',kana:'そご',zh:'齟齬',en:'discrepancy/inconsistency'},
    {word:'是正',kana:'ぜせい',zh:'糾正',en:'correction/rectification'},
    {word:'緩和',kana:'かんわ',zh:'緩和',en:'relaxation/alleviation'},
    {word:'軽減',kana:'けいげん',zh:'減輕',en:'reduction/alleviation'},
    {word:'増強',kana:'ぞうきょう',zh:'增強',en:'strengthening/reinforcement'},
    {word:'拡充',kana:'かくじゅう',zh:'擴充',en:'expansion/enhancement'},
    {word:'刷新',kana:'さっしん',zh:'革新',en:'renewal/reform'},
    {word:'再構築',kana:'さいこうちく',zh:'重新構築',en:'reconstruction/rebuilding'},
    {word:'形骸化',kana:'けいがいか',zh:'流於形式',en:'formalization/hollowing out'},
    {word:'骨抜き',kana:'ほねぬき',zh:'抽去骨幹/架空',en:'emasculation/gutting'},
    {word:'形而上',kana:'けいじじょう',zh:'形而上',en:'metaphysical'},
    {word:'帰納',kana:'きのう',zh:'歸納',en:'induction'},
    {word:'演繹',kana:'えんえき',zh:'演繹',en:'deduction'},
    {word:'俯瞰',kana:'ふかん',zh:'俯瞰',en:'bird\'s eye view'},
    {word:'内省',kana:'ないせい',zh:'內省',en:'introspection'},
    {word:'渾身',kana:'こんしん',zh:'渾身',en:'with all one\'s strength'},
    {word:'夙に',kana:'つとに',zh:'早就',en:'long ago/for a long time'},
    {word:'あわよくば',kana:'あわよくば',zh:'如果順利的話',en:'if lucky/with luck'},
    {word:'ひいては',kana:'ひいては',zh:'進而',en:'and furthermore'},
    {word:'もとより',kana:'もとより',zh:'本來就',en:'from the beginning'},
    {word:'おのずから',kana:'おのずから',zh:'自然而然',en:'naturally/spontaneously'},
    {word:'ひとえに',kana:'ひとえに',zh:'完全是',en:'solely/entirely'},
    {word:'おおよそ',kana:'おおよそ',zh:'大約',en:'approximately/generally'},
    {word:'すこぶる',kana:'すこぶる',zh:'非常',en:'extremely/very much'},
    {word:'いかんせん',kana:'いかんせん',zh:'無奈',en:'unfortunately/it\'s regrettable'},
    {word:'蓋し',kana:'けだし',zh:'想必',en:'certainly/presumably'},
    {word:'畢竟',kana:'ひっきょう',zh:'畢竟',en:'after all/in the end'},
    {word:'寧ろ',kana:'むしろ',zh:'寧可',en:'rather/if anything'},
    {word:'概して',kana:'おおむね',zh:'大體上',en:'generally speaking'},
    {word:'専ら',kana:'もっぱら',zh:'專門',en:'exclusively/mainly'},
    {word:'漸く',kana:'ようやく',zh:'終於',en:'finally/barely'},
    {word:'却って',kana:'かえって',zh:'反而',en:'on the contrary'},
    {word:'ひとしきり',kana:'ひとしきり',zh:'一陣子',en:'for a while'},
    {word:'いみじくも',kana:'いみじくも',zh:'恰如其分地',en:'aptly/fittingly'},
    {word:'期せずして',kana:'きせずして',zh:'不期而然',en:'unexpectedly'},
    {word:'折りしも',kana:'おりしも',zh:'正好在那時',en:'just then/at that moment'},
    {word:'虚を突く',kana:'きょをつく',zh:'出其不意',en:'to catch off guard'},
    {word:'不断',kana:'ふだん',zh:'不斷',en:'constant/ceaseless'},
    {word:'歴然',kana:'れきぜん',zh:'歷歷分明',en:'evident/obvious'},
    {word:'抜群',kana:'ばつぐん',zh:'出類拔萃',en:'outstanding/exceptional'},
    {word:'卑近',kana:'ひきん',zh:'淺顯易懂',en:'familiar/close at hand'},
    {word:'厳粛',kana:'げんしゅく',zh:'嚴肅',en:'solemn/grave'},
    {word:'謙虚',kana:'けんきょ',zh:'謙虛',en:'humble/modest'},
    {word:'傲慢',kana:'ごうまん',zh:'傲慢',en:'arrogant/haughty'},
    {word:'清廉',kana:'せいれん',zh:'清廉',en:'honest/upright'},
    {word:'頑固',kana:'がんこ',zh:'頑固',en:'stubborn/obstinate'},
    {word:'柔和',kana:'にゅうわ',zh:'溫柔和善',en:'gentle/mild'}
  ]
};
